// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(UygulamaContext))]
    [Migration("20251210001540_Baslangic")]
    partial class Baslangic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Antrenor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("BaslangicSaati")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("BitisSaati")
                        .HasColumnType("time");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SporSalonuId")
                        .HasColumnType("int");

                    b.Property<string>("UzmanlikAlani")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SporSalonuId");

                    b.ToTable("Antrenorler");
                });

            modelBuilder.Entity("WebApplication1.Models.AntrenorHizmet", b =>
                {
                    b.Property<int>("AntrenorId")
                        .HasColumnType("int");

                    b.Property<int>("HizmetId")
                        .HasColumnType("int");

                    b.HasKey("AntrenorId", "HizmetId");

                    b.HasIndex("HizmetId");

                    b.ToTable("AntrenorHizmetler");
                });

            modelBuilder.Entity("WebApplication1.Models.Hizmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SporSalonuId")
                        .HasColumnType("int");

                    b.Property<int>("SureDakika")
                        .HasColumnType("int");

                    b.Property<decimal>("Ucret")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SporSalonuId");

                    b.ToTable("Hizmetler");
                });

            modelBuilder.Entity("WebApplication1.Models.SporSalonu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("AcilisSaati")
                        .HasColumnType("time");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("KapanisSaati")
                        .HasColumnType("time");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SporSalonları");
                });

            modelBuilder.Entity("WebApplication1.Models.Antrenor", b =>
                {
                    b.HasOne("WebApplication1.Models.SporSalonu", "SporSalonu")
                        .WithMany("Antrenorler")
                        .HasForeignKey("SporSalonuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SporSalonu");
                });

            modelBuilder.Entity("WebApplication1.Models.AntrenorHizmet", b =>
                {
                    b.HasOne("WebApplication1.Models.Antrenor", "Antrenor")
                        .WithMany("AntrenorHizmetler")
                        .HasForeignKey("AntrenorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Hizmet", "Hizmet")
                        .WithMany("AntrenorHizmetler")
                        .HasForeignKey("HizmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Antrenor");

                    b.Navigation("Hizmet");
                });

            modelBuilder.Entity("WebApplication1.Models.Hizmet", b =>
                {
                    b.HasOne("WebApplication1.Models.SporSalonu", "SporSalonu")
                        .WithMany("Hizmetler")
                        .HasForeignKey("SporSalonuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SporSalonu");
                });

            modelBuilder.Entity("WebApplication1.Models.Antrenor", b =>
                {
                    b.Navigation("AntrenorHizmetler");
                });

            modelBuilder.Entity("WebApplication1.Models.Hizmet", b =>
                {
                    b.Navigation("AntrenorHizmetler");
                });

            modelBuilder.Entity("WebApplication1.Models.SporSalonu", b =>
                {
                    b.Navigation("Antrenorler");

                    b.Navigation("Hizmetler");
                });
#pragma warning restore 612, 618
        }
    }
}
